<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Laporan Transaksi Pet Hotel Bulanan</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            color: #333;
        }
        h2 {
            text-align: center;
            color: #4CAF50;
            margin-bottom: 20px;
            font-size: 24px;
        }
        h3 {
            text-align: right;
            color: #333;
            margin-top: 20px;
            font-size: 18px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        th, td {
            padding: 12px;
            text-align: center;
            border: 1px solid #ddd;
        }
        th {
            background-color: #4CAF50;
            color: white;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        tr:hover {
            background-color: #f1f1f1;
        }
        .total-harga {
            font-size: 18px;
            font-weight: bold;
            color: #4CAF50;
        }
        .no-data {
            text-align: center;
            color: #888;
            font-style: italic;
            padding: 20px;
        }
		.footer {
            text-align: center;
            margin-top: 30px;
            color: #888;
            font-size: 12px;
            padding: 10px;
            background-color: #f4f4f4;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
    </style>
</head>
<body>
    <h2>Laporan Transaksi Pet Hotel Bulan <?php echo date('F Y', strtotime($bulan)); ?></h2>
    <table>
        <thead>
            <tr>
                <th>No</th>
                <th>Nama Pemilik</th>
                <th>Nama Hewan</th>
                <th>Tanggal Check-in</th>
                <th>Tanggal Check-out</th>
                <th>Total Harga</th>
            </tr>
        </thead>
        <tbody>
            <?php if (!empty($transaksi)): ?>
                <?php $no = 1; ?>
                <?php foreach ($transaksi as $tr) : ?>
                    <tr>
                        <td><?php echo $no++; ?></td>
                        <td><?php echo $tr->user_name; ?></td>
                        <td><?php echo $tr->cat_name; ?></td>
                        <td><?php echo date('d-m-Y', strtotime($tr->date_checkin)); ?></td>
                        <td><?php echo date('d-m-Y', strtotime($tr->date_checkout)); ?></td>
                        <td>Rp <?php echo number_format($tr->total_price, 0, ',', '.'); ?></td>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td colspan="6" class="no-data">Tidak ada data transaksi untuk bulan ini.</td>
                </tr>
            <?php endif; ?>
        </tbody>
    </table>

    <h3>
        Total Harga: <span class="total-harga">Rp <?php echo number_format($total_harga['total_harga'], 0, ',', '.'); ?></span>
    </h3>

	<div class="footer">
        Generated by Management System
    </div>
</body>
</html>
